import { FuzzyResult } from "@/lib/fuzzy-engine";
import { LearningProfile } from "@/lib/adaptive-engine";
import { TomorrowForecast } from "@/lib/predictive-engine";

export type PlanType = 'Recommended' | 'Deep Work' | 'Recovery';

export interface ExpectedOutcomes {
  knowledgeCoverage: number; // 0-100%
  mentalLoad: number; // 0-100%
  expectedFatigue: number; // 0-100%
  recoveryRequirement: string; // "Low", "Medium", "High"
  completionProbability: number; // 0-100%
}

export interface MultiCriteria {
  efficiency: number;
  recovery: number;
  consistency: number;
  difficulty: number;
  learningDepth: number;
  motivation: number;
}

export interface StudyPlan {
  id: string;
  type: PlanType;
  duration: number;
  breakTime: number; // total break time in minutes
  description: string;
  pros: string[];
  cons: string[];
  outcomes: ExpectedOutcomes;
  criteria: MultiCriteria;
  score: number; // For ranking
  rankTitle?: string; // e.g. "🥇 Best Overall"
}

export interface DecisionContext {
  fuzzyResult: FuzzyResult;
  profile: LearningProfile | null;
  forecast: TomorrowForecast | null;
}

const calculateCriteriaScore = (c: MultiCriteria) => {
  return (c.efficiency * 1.5) + (c.recovery * 1.2) + c.consistency + c.learningDepth - (c.difficulty * 0.5) + c.motivation;
};

export function generateAlternativePlans(context: DecisionContext): StudyPlan[] {
  const { fuzzyResult, profile, forecast } = context;
  const baseDuration = fuzzyResult.duration;
  
  // Base current context
  const currentFatigue = profile?.averageFatigue || 50;
  const currentFocus = profile?.averageFocus || 50;
  const futureFatigue = forecast?.predictedFatigue || currentFatigue;

  // Plan A: Recommended (The exact Fuzzy Output)
  const recommended: StudyPlan = {
    id: 'plan-recommended',
    type: 'Recommended',
    duration: baseDuration,
    breakTime: Math.round(baseDuration * 0.2), // 20% break time roughly
    description: 'Balanced session generated by the AI based on your current inputs.',
    pros: [
      'Perfectly tuned to your current focus and fatigue',
      'Balanced learning depth and recovery'
    ],
    cons: [
      'May not push your limits',
      'Standard progression'
    ],
    outcomes: {
      knowledgeCoverage: 75,
      mentalLoad: 50,
      expectedFatigue: Math.min(100, currentFatigue + 20),
      recoveryRequirement: 'Medium',
      completionProbability: 85,
    },
    criteria: {
      efficiency: 80,
      recovery: 70,
      consistency: 85,
      difficulty: 50,
      learningDepth: 75,
      motivation: 80,
    },
    score: 0
  };
  recommended.score = calculateCriteriaScore(recommended.criteria);

  // Plan B: Deep Work (1.5x duration)
  const deepWorkDuration = Math.round(baseDuration * 1.5);
  const deepWork: StudyPlan = {
    id: 'plan-deep-work',
    type: 'Deep Work',
    duration: deepWorkDuration,
    breakTime: Math.round(deepWorkDuration * 0.15), // Less frequent breaks
    description: 'Extended intense session prioritizing topic coverage over comfort.',
    pros: [
      'Maximum knowledge coverage',
      'High learning depth and flow state'
    ],
    cons: [
      'Significantly increases mental fatigue',
      'Requires longer recovery afterwards'
    ],
    outcomes: {
      knowledgeCoverage: 95,
      mentalLoad: 85,
      expectedFatigue: Math.min(100, currentFatigue + 45),
      recoveryRequirement: 'High',
      completionProbability: 60,
    },
    criteria: {
      efficiency: 95,
      recovery: 30,
      consistency: 60,
      difficulty: 90,
      learningDepth: 95,
      motivation: 65,
    },
    score: 0
  };
  deepWork.score = calculateCriteriaScore(deepWork.criteria);

  // Plan C: Recovery (0.5x duration)
  const recoveryDuration = Math.max(15, Math.round(baseDuration * 0.5));
  const recovery: StudyPlan = {
    id: 'plan-recovery',
    type: 'Recovery',
    duration: recoveryDuration,
    breakTime: Math.round(recoveryDuration * 0.3), // 30% break time
    description: 'Short, light session focused on maintaining consistency without burnout.',
    pros: [
      'Maintains daily study streak',
      'Prevents burnout and lowers mental load'
    ],
    cons: [
      'Minimal new topic coverage',
      'Not suitable for urgent deadlines'
    ],
    outcomes: {
      knowledgeCoverage: 35,
      mentalLoad: 20,
      expectedFatigue: Math.max(0, currentFatigue - 10), // Might actually reduce subjective fatigue
      recoveryRequirement: 'Low',
      completionProbability: 98,
    },
    criteria: {
      efficiency: 50,
      recovery: 95,
      consistency: 95,
      difficulty: 20,
      learningDepth: 40,
      motivation: 90,
    },
    score: 0
  };
  recovery.score = calculateCriteriaScore(recovery.criteria);

  // Rank logic
  let plans = [recommended, deepWork, recovery];
  
  // Context-aware adjustments to scores
  if (futureFatigue > 75) {
    // If predicted fatigue is very high, penalize Deep Work and boost Recovery
    plans.find(p => p.type === 'Deep Work')!.score -= 50;
    plans.find(p => p.type === 'Recovery')!.score += 30;
  }
  if (currentFocus > 80) {
    // If focus is exceptionally high, boost Deep Work
    plans.find(p => p.type === 'Deep Work')!.score += 40;
  }

  // Sort by score
  plans.sort((a, b) => b.score - a.score);

  // Assign titles
  plans[0].rankTitle = '🥇 Best Overall';
  
  // Find lowest fatigue for title
  const lowestFatigue = [...plans].sort((a, b) => a.outcomes.expectedFatigue - b.outcomes.expectedFatigue)[0];
  if (lowestFatigue.type !== plans[0].type) {
    lowestFatigue.rankTitle = '🥈 Lowest Fatigue';
  }

  // Find fastest completion
  const fastest = [...plans].sort((a, b) => a.duration - b.duration)[0];
  if (fastest.type !== plans[0].type && fastest.type !== lowestFatigue.type) {
    fastest.rankTitle = '🥉 Fastest Completion';
  }

  // Fallbacks if overlaps happen
  plans.forEach(p => {
    if (!p.rankTitle) p.rankTitle = 'Alternative Choice';
  });

  return plans;
}

export function generateDecisionAdvice(context: DecisionContext, topPlan: StudyPlan): { advice: string, evidence: string[] } {
  const { fuzzyResult, profile, forecast } = context;
  let advice = "";
  let evidence: string[] = [];

  evidence.push(`Mamdani Fuzzy Output: ${fuzzyResult.duration} minutes (Confidence: ${fuzzyResult.confidence}%)`);

  if (topPlan.type === 'Deep Work') {
    advice = "Your recent focus metrics indicate you are in an excellent state for a Deep Work session today.";
    if (profile) evidence.push(`Historical Average Focus: ${profile.averageFocus}%`);
    if (forecast) evidence.push(`Predicted Focus for tomorrow: ${forecast.predictedFocus}%`);
  } else if (topPlan.type === 'Recovery') {
    advice = "Your fatigue indicators are quite high. A Recovery Session is strongly advised to prevent burnout while maintaining consistency.";
    if (profile) evidence.push(`Historical Average Fatigue: ${profile.averageFatigue}%`);
    if (forecast) evidence.push(`Predicted Fatigue if continuing trend: ${forecast.predictedFatigue}%`);
  } else {
    advice = "A balanced, standard session is the most optimal choice for your current state. It provides steady progress without overexertion.";
    evidence.push(`No extreme fatigue or focus anomalies detected in historical data.`);
  }

  return { advice, evidence };
}
